import { Suspense } from "react";
import ShopClient from "../../components/ShopClient";

export const metadata = {
  title: "Shop — Apeak Product Catalog",
  description:
    "Browse the complete Apeak catalog: 3D press-on nails, clear and white nails, daisy bottles, rabbit bottles, mugs, candy trays, and more.",
  keywords: [
    "press-on nails india", "artificial nails", "stick-on nails", "reusable press-on nails", 
    "salon-quality nails at home", "best press-on nail brands in India",
    "glass water bottle online india", "borosilicate glass water bottle", "aesthetic glass water bottle", 
    "glass water bottle with bamboo lid", "leak-proof glass water bottle",
    "kitchen storage organizer", "aesthetic home products online india", "unique gifts for girls",
    "press on nails", "press on nails short", "press on nails almond", "press on nails coffin", 
    "press on nails square", "press on nails stiletto", "press on nails french tip", "press on nails with glue", "press on nails adhesive tabs", 
    "press on nails reusable", "press on nails custom", "press on nails handmade", "press on nails luxury", "press on nails design", "press on nails trendy", "press on nails aesthetic", "press on nails cute", "press on nails nude", 
    "press on nails pink", "press on nails white", "press on nails black", "press on nails red", "press on nails chrome", "press on nails glazed", "press on nails cat eye", "press on nails magnetic", "press on nails glitter", "press on nails matte", "press on nails glossy", "press on nails 3d", "press on nails floral", "press on nails marble", "press on nails swirls", "press on nails ombre", "press on nails jelly", "press on nails y2k", "press on nails coquette", 
    "press on nails cottagecore", "press on nails gothic", "press on nails minimalist", "press on nails natural", "press on nails bridal", "press on nails wedding", "press on nails party", "press on nails holiday", "press on nails christmas", "press on nails halloween", "press on nails fall", "press on nails winter", "press on nails summer", "press on nails spring", "press on nails extra short", "press on nails extra long", "press on nails small nail bed", "press on nails wide nail bed", "press on nails petite", "press on nails kit", "press on nails set", "press on nails pack", "press on nails bulk", "press on nails wholesale", "press on nails cheap", "press on nails under 10", "press on nails under 5", "press on nails amazon", 
    "press on nails shein", "press on nails etsy", "press on nails tiktok", "fake nails", "fake nails for women", "fake nails for girls", "fake nails for kids", "fake nails short", "fake nails long", "fake nails almond", "fake nails coffin", "fake nails square", "fake nails stiletto", "fake nails oval", "fake nails french tip", "fake nails design", "fake nails cute", "fake nails aesthetic", "fake nails natural", "fake nails stick on", "fake nails glue on", "fake nails reusable", "fake nails clear", "fake nails colored", "fake nails glitter", "fake nails matte", "fake nails pack 100", "fake nails pack 24", "stick on nails", "stick on nails for women", 
    "stick on nails short", "stick on nails long", "stick on nails french", "stick on nails almond", "stick on nails square", "stick on nails design", "stick on nails reusable", "stick on nails with glue", "stick on nails tabs", "stick on nails kids", "artificial nails", "artificial nails short", "artificial nails french", "artificial nails design", "artificial nails kit", "artificial nails glue", "artificial nails reusable", "false nails", "false nails short", "false nails long", "false nails almond", "false nails coffin", "false nails french", "false nails design", "false nails kit", "false nails pack", "soft gel tips", "full cover tips", "gel x nails", "gel x tips", 
    "nail tips", "nail tips clear", "nail tips almond", "nail tips coffin", "nail tips square", "nail glue", "brush on nail glue", "super strong nail glue", "waterproof nail glue", "fast drying nail glue", "long lasting nail glue", "nail adhesive tabs", "sticky nail tabs", "double sided nail tabs", "nail prep kit", "cuticle pusher", "wooden cuticle stick", "nail buffer block", "mini nail file", "glass nail file", "crystal nail file", "nail dehydrator", "nail alcohol wipes", "nail glue remover", "how to apply press on nails", "how to remove press on nails", "how long do press on nails last", "press on nails tutorial", "press on nails vs acrylics", "press on nails sizing", "nail sizing kit", "nail stand", "press on nails packaging", "kids press on nails", "press on nails for kids", "children press on nails", "toddler press on nails", "safe fake nails for kids", "peel off fake nails kids", "kids nail stickers", "kids stick on nails", "cartoon press on nails", "cute kids fake nails", "baby nail trimmer", "electric baby nail trimmer", "baby nail clipper", 
    "infant nail clipper", "newborn nail trimmer", "safe baby nail cutter", "electric baby nail file", "baby grooming kit", "infant manicure set", "toddler nail clipper", "baby nail scissors", "anti pinch baby clipper", "compact mirror", "compact mirror with light", "led compact mirror", "travel compact mirror", "purse compact mirror", "pocket mirror", "pocket mirror for women", "pocket mirror for purse", "mini pocket mirror", "small pocket mirror", "cute pocket mirror", "aesthetic pocket mirror", "folding pocket mirror", "round pocket mirror", "square pocket mirror", "magnifying compact mirror", "magnifying pocket mirror", "10x magnifying mirror", "5x magnifying mirror", "2x magnifying mirror", "dual sided compact mirror", "lighted travel mirror", "rechargeable led mirror", "hand mirror", "hand mirror with handle", "handheld mirror", "vanity hand mirror", "vintage hand mirror", "antique hand mirror", "baroque hand mirror", "carved hand mirror", "gold hand mirror", "aesthetic hand mirror",
     "cute hand mirror", "retro hand mirror", "tabletop vanity mirror", "desk mirror aesthetic", "wavy mirror desk", "cloud desk mirror", "irregular desk mirror", "mirror with comb", "compact mirror with brush", "folding hair brush mirror", "pop up brush mirror", "travel brush with mirror", "glass water bottle", "glass water bottle with straw", "glass water bottle with bamboo lid", "glass water bottle with silicone sleeve", "glass water bottle aesthetic", "aesthetic glass water bottle", "cute glass water bottle", "borosilicate glass bottle", "borosilicate water bottle", "reusable glass bottle", "eco friendly glass bottle", "bpa free glass bottle", "leakproof glass bottle", "dishwasher safe glass bottle", "wide mouth glass bottle", "clear glass water bottle", "frosted glass water bottle", "glass water bottle 32 oz", "glass water bottle 1 litre", "glass water bottle 500ml", "glass water bottle 16 oz", "glass water bottle 24 oz", "small glass water bottle", "mini glass water bottle", 
     "square glass water bottle", "flat water bottle", "a5 memo bottle", "slim water bottle", "glass tumbler with straw", "iced coffee glass tumbler", "aesthetic tumbler cup", "glass smoothie cup", "glass boba cup", "glass travel mug", "water bottle with time marker", "motivational water bottle", "inspirational water bottle", "tracker water bottle", "aesthetic water bottle", "cute water bottle", "pastel water bottle", "kawaii water bottle", "kawaii water bottle with strap", "cute water bottle for girls", "cute water bottle for school", "cute water bottle for gym", "cute water bottle for office", "bear water bottle", "rabbit water bottle", "donut water bottle", "kids water bottle", "kids sipper bottle", "toddler water bottle", "insulated water bottle", "stainless steel water bottle", "vacuum flask bottle", "thermos water bottle", "cold water bottle", "hot water bottle thermos", "fruit infuser water bottle", "detox water bottle", "tea infuser bottle", "infuser water bottle glass", "kitchen organizer", "kitchen storage", "kitchen organization ideas", "countertop organizer", "kitchen counter organizer", "pantry organizer", "pantry storage bins", "clear pantry bins", "spice organizer", "spice rack organizer", "rotating spice rack", "lazy susan organizer", "lazy susan turntable", "cabinet organizer", "kitchen cabinet shelves", "2 tier kitchen organizer", "under sink organizer", "under sink pull out shelves", "drawer organizer kitchen", "cutlery tray organizer", "utensil organizer drawer", "knife block in drawer", "dish drying rack", 
     "over sink dish rack", "sponge holder for sink", "sink caddy organizer", "paper towel holder stand", "pot and pan organizer", "pan rack for cabinet", "pot lid organizer", "cutting board organizer", "modular food storage", "airtight food containers", "glass food storage jars", "borosilicate storage jars", "bamboo lid glass jars", "airtight glass canisters", "spice jars with labels", "minimalist spice jars", "cereal dispenser countertop", "rice dispenser container", "fridge organizer bins", "clear fridge storage", "egg organizer for fridge", "can organizer for pantry", "produce storage containers", "serving tray", "decorative serving tray", "wooden serving tray", "acrylic serving tray", "mirror vanity tray", "gold serving tray", "round serving tray", "rectangle serving tray", "breakfast in bed tray", "coffee table tray", "ottoman tray decorative", "snack serving tray", "divided serving tray", "snack tray with lid", "rotating snack tray", "flower snack box", "dry fruit tray", "nut serving tray", "candy dish with lid", "glass candy jar", "festive serving bowls", "decorative glass bowls", "crystal serving bowls", "dessert bowls glass", "glass fruit bowl", "salad bowl with servers", "dip bowls set", "condiment serving set", "charcuterie board accessories", "tabletop organizer", "desk organizer", "desk organization aesthetic", "aesthetic desk organizer", "acrylic desk organizer", "desktop storage box", "stationery organizer", "pen holder for desk", "pencil cup aesthetic", "makeup organizer", "acrylic makeup organizer", "cosmetic storage box", "skincare organizer shelf", "rotating makeup organizer", "makeup brush holder", "lipstick organizer display", "perfume display stand", "jewelry organizer", "jewelry storage box", "earring holder stand", "necklace hanger organizer", "ring tray aesthetic", "trinket dish cute", "bedside table organizer", "nightstand tray", "cable management box", "cord organizer desk", "aesthetic room decor", "cute room decor", "korean room decor", "pastel room decor", "coquette room decor", "cottagecore room decor", "y2k room decor", "scandinavian room decor", "minimalist home decor", "aesthetic home finds", "pinterest room decor", "tiktok home finds", 
    "amazon home finds", "viral home products", "trending room accessories", "sunset projection lamp", "acrylic memo board", "wire wall grid", "fairy lights battery operated", "bubble candle aesthetic", "scented soy candle", "ceramic flower vase", "donut vase aesthetic", "aesthetic coffee mug", "cute stationery items", "korean stationery online", "pastel highlighters set", "aesthetic gel pens", "washi tape aesthetic", "sticky notes cute", "aesthetic phone charms", "beaded phone wristlet", "cute keychains aesthetic", "plush keychain cute", "aesthetic tote bag", "canvas tote bag aesthetic", "cute makeup bag", "cosmetic pouch aesthetic", "cute aesthetic gifts", "aesthetic gifts for her", "cute gifts for best friend", "gift ideas for teenage girls", "birthday gifts for bestie", "girlfriend gift ideas", "self care gift basket", "aesthetic gift basket", "budget friendly aesthetic gifts", "gifts under 25", "gifts under 15", "trending products 2026", "viral tiktok products", "trending aesthetic items"
  ],
};

export default function ShopPage() {
  return (
    <Suspense
      fallback={
        <div style={{ textAlign: "center", padding: "100px 20px" }}>
          Loading catalog...
        </div>
      }
    >
      <ShopClient />
    </Suspense>
  );
}
